// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkbpyiqzjdqlpeyrgbak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrYnB5aXF6amRxbHBleXJnYmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NjMwMDYsImV4cCI6MjA1NzUzOTAwNn0.U2KZu6hcsrRs1oJWqXJ36V_s6x0nN9axKDLDSdQYPA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);